### ISSUE TITLE
Can't backup addon by service call

### ISSUE THREAD

**Issue by Erelen-Laiquendi** [hassio-addons/addon-uptime-kuma#169]
# Problem/Motivation

Service call:
```yaml
service: hassio.backup_partial
data:
  addons:
    - a0d7b954_uptime-kuma
```

Result: `Failed to call service hassio.backup_partial. invalid slug a0d7b954_uptime-kuma (try a0d7b954_uptime_kuma) @ data['addons'][0]. Got None`

With `a0d7b954_uptime_kuma` slug - HA doesn't create any backup (as with any another formally allowed slug - "qwerty", for example)

## Expected behavior

Creating partial backup with Uptime Kuma addon

Or, please, tell me any another way to backup this addon by service call.
